name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-west-1 
          role-arn: arn:aws:iam::939895954199:role/ecr_role

      - name: Build Docker image
        run: docker build -t 939895954199.dkr.ecr.us-west-1.amazonaws.com/hrhouz-img:v1 .

      - name: Tag the image for ECR
        run: docker tag 939895954199.dkr.ecr.us-west-1.amazonaws.com/hrhouz-img:v1 939895954199.dkr.ecr.us-west-1.amazonaws.com/hrhouz-img:latest

      - name: Push image to ECR
        run: docker push 939895954199.dkr.ecr.us-west-1.amazonaws.com/hrhouz-img:latest


