name: Terraform Workflow

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      write-only: packages # Adjust permissions as needed

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }} # Replace with your region secret
          role-arn: ${{ secrets.AWS_ROLE_ARN }}  # Replace with your role ARN secret
          # Alternatively, for OIDC:
          # use-oidc-token: true  # If using OpenID Connect
          # audience: 'your-audience'  # Optional for OIDC

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (Pull Request)
        if: github.event_name == 'push'
        run: terraform plan -no-color -input=false

      - name: Terraform Apply (Main Branch Push)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Plan Status (Pull Request)
        if: steps.plan.outcome == 'failure' && github.event_name == 'push'
        run: exit 1
