name: Terraform Plan and Apply

on:
  workflow_dispatch:
    branches: [ main ]


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform code (optional)
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: |
          export TF_IN_AUTOMATION=true  # Optional flag for Terraform Cloud/Enterprise
          terraform plan -detailed-exitcode

      - name: Check if plan has changes
        run: |
          if [[ ${{ steps.plan.outputs.exitcode }} -eq 2 ]]; then
            echo "Terraform plan has changes. Please review before applying."
            exit 1
          fi

      - name: Apply Terraform (optional)
        if: ${{ steps.plan.outputs.exitcode }} == 2  # Only apply if plan has changes
        run: |
          export TF_IN_AUTOMATION=true  # Optional flag for Terraform Cloud/Enterprise
          terraform apply -auto-approve


