name: Terraform Infrastructure Management

on:
  push:
    branches: [ main ]

jobs:
  manage-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.2"

      - name: Initialize Terraform
        run: terraform init

      - name: Check if infrastructure exists
        run: |
          terraform plan -destroy | grep -q "No changes. Infrastructure is up to date." && exit 0 || exit 1

      - name: Destroy existing infrastructure (if found)
        if: steps.check-exists.outputs == '1'
        run: terraform destroy

      - name: Apply infrastructure changes (if not found)
        if: steps.check-exists.outputs == '0'
        run: terraform apply -auto-approve

