name: Terraform Destroy

on:
  workflow_dispatch: # Triggered manually

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      write-only: packages # Adjust permissions as needed

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }} # Replace with your region secret
          role-arn: ${{ secrets.AWS_ROLE_ARN }}  # Replace with your role ARN secret
          # Alternatively, for OIDC:
          # use-oidc-token: true  # If using OpenID Connect
          # audience: 'your-audience'  # Optional for OIDC

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Destroy (Manual Confirmation)
        run: |
          echo "**WARNING:** This will destroy your infrastructure in ${AWS_REGION}!"
          read -r -p "Are you sure you want to continue? (y/N) " response
          case "$response" in
            [yY]*)
              terraform destroy -auto-approve -input=false
              ;;
            *)
              echo "Destruction cancelled."
              exit 0
              ;;
          esac

